In [1]:
### Pandas-DataFrame and Series

import pandas as pd

In [3]:
### Series
# A pandas series is a one_dimentional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series :\n",series )
print(type(series))

Series :
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [4]:
## Create a Series from dictionary
import pandas as pd
data={'a': 1,'b': 2,'c': 3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [7]:
### Dataframe
## A Dataframe is a two-dimensional,size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

# Create a Dataframe from a dictionary of list

data={
    'Name' : ['Govind','Vasudev','Madhav'],
    'Age' : [21,20,19],
    'City' : ['Mumbai','Ahemdabad','Bangalore']  
}
df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0   Govind   21     Mumbai
1  Vasudev   20  Ahemdabad
2   Madhav   19  Bangalore
<class 'pandas.DataFrame'>

In [8]:
## Create a Dataframe from a List of Dictionaries

data=[
    {'Name':'Govind', 'Age':32 , 'City':'Vrindavan'},
     {'Name':'Sweety', 'Age':20 , 'City':'Ahemdabad'},
      {'Name':'Radha', 'Age':19 , 'City':'Mathura'},
       {'Name':'Ayushi', 'Age':22 , 'City':'Goa'}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0  Govind   32  Vrindavan
1  Sweety   20  Ahemdabad
2   Radha   19    Mathura
3  Ayushi   22        Goa
<class 'pandas.DataFrame'>

In [37]:
import pandas as pd
df=pd.read_csv('sales_data.csv')
df.head(5)

,category,rating,text,label,clean_text
0,Home_and_Kitchen,5.0,"Love this! Well made, sturdy, and very comfor...",1,love well made sturdy comfortable love itvery ...
1,Home_and_Kitchen,5.0,"love it, a great upgrade from the original. I...",1,love great upgrade original ive mine couple years
2,Home_and_Kitchen,5.0,This pillow saved my back. I love the look and...,1,pillow saved back love look feel pillow
3,Home_and_Kitchen,1.0,"Missing information on how to use it, but it i...",1,missing information use great product price
4,Home_and_Kitchen,5.0,Very nice set. Good quality. We have had the s...,1,nice set good quality set two months

In [4]:
df.tail(5)

,category,rating,text,label,clean_text
40521,Beauty,4.0,The shampoo has a pleasant scent and cleans we...,1,shampoo pleasant scent cleans well virtual ass...
40522,Clothing,3.0,The jacket is stylish but not very warm. As pe...,1,jacket stylish warm per aigenerated review sui...
40523,Sporting Goods,5.0,The running shoes provide excellent support. A...,1,running shoes provide excellent support automa...
40524,Food,4.0,The pasta cooks perfectly every time. Accordin...,1,pasta cooks perfectly every time according ai ...
40525,Automotive,3.0,The car freshener has a strong scent. As per a...,1,car freshener strong scent per virtual assista...

In [11]:
### Accessing Data from Dataframe
df

      Name  Age       City
0   Govind   21     Mumbai
1  Vasudev   20  Ahemdabad
2   Madhav   19  Bangalore

In [12]:
df['Name']

0     Govind
1    Vasudev
2     Madhav
Name: Name, dtype: object

In [13]:
df.loc[0]

Name    Govind
Age         21
City    Mumbai
Name: 0, dtype: object

In [15]:
df.iloc[0][2]

C:\Users\HP\AppData\Local\Temp\ipykernel_1408\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Mumbai'

In [20]:
### Accessing a specified element
print(df.at[1,'Age'])
print(df.at[2,'Name'])

20
Madhav

In [21]:
### Accessing a specified element using iat
print(df.iat[2,2])

Bangalore

In [22]:
### Data Manipulation with Dataframe
df

      Name  Age       City
0   Govind   21     Mumbai
1  Vasudev   20  Ahemdabad
2   Madhav   19  Bangalore

In [31]:
### Adding a column
df['Salary']=[50000,77000,80000]
df

      Name  Age       City  Salary
0   Govind   21     Mumbai   50000
1  Vasudev   20  Ahemdabad   77000
2   Madhav   19  Bangalore   80000

In [32]:
### Removing a column
df.drop('Salary' ,axis=1,inplace=True)

In [33]:
df

      Name  Age       City
0   Govind   21     Mumbai
1  Vasudev   20  Ahemdabad
2   Madhav   19  Bangalore

In [35]:
## Update Age 
df['Age'] = df['Age']+5
df

      Name  Age       City
0   Govind   27     Mumbai
1  Vasudev   26  Ahemdabad
2   Madhav   25  Bangalore

In [36]:
df.drop(0,inplace=True)
df

      Name  Age       City
1  Vasudev   26  Ahemdabad
2   Madhav   25  Bangalore

In [39]:
# Display the data types of each column
print("Data types :\n",df.dtypes)

# describe the Dataframe
print("Statistical summary :\n",df.describe())

Data types :
 category       object
rating        float64
text           object
label           int64
clean_text     object
dtype: object
Statistical summary :
              rating         label
count  40526.000000  40526.000000
mean       4.255416      0.500765
std        1.144287      0.500006
min        1.000000      0.000000
25%        4.000000      0.000000
50%        5.000000      1.000000
75%        5.000000      1.000000
max        5.000000      1.000000

In [41]:
df.describe()

             rating         label
count  40526.000000  40526.000000
mean       4.255416      0.500765
std        1.144287      0.500006
min        1.000000      0.000000
25%        4.000000      0.000000
50%        5.000000      1.000000
75%        5.000000      1.000000
max        5.000000      1.000000